#! /usr/bin/env bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace # Uncomment this line for debugging purposes

# Load libraries
. /opt/lib/logging
. /opt/lib/bitnami
. /opt/lib/kafka

# Load Kafka environment variables
. /opt/lib/environment

print_welcome_page

if [[ "$*" = *"/opt/kafka/run"* || "$*" = *"/run.sh"* ]]; then
    info "** Starting Kafka setup **"
    /opt/kafka/setup.sh
    info "** Kafka setup finished! **"
fi

echo ""
exec "$@"
